"""Offline fixed-route checkpoint navigation foundation."""

from .contracts import (
    ArrivalEvidence,
    Checkpoint,
    CheckpointMatchKind,
    CheckpointObservation,
    CheckpointRole,
    CheckpointSourceIdentity,
    FrameProvenance,
    NavigationFailureReason,
    NavigationPhase,
    NavigationPolicy,
    NavigationStop,
    NavigationTransition,
    NavigationTransitionOutcome,
    OfflineStepProposal,
    RouteDirection,
    RouteEndpoint,
    RouteEndpointRole,
    RouteEvaluationContext,
    RouteIdentity,
    RoutePlan,
    RouteProgress,
    RouteStep,
)
from .machine import observe_checkpoint, prepare_step, start_route

__all__ = [
    "ArrivalEvidence",
    "Checkpoint",
    "CheckpointMatchKind",
    "CheckpointObservation",
    "CheckpointRole",
    "CheckpointSourceIdentity",
    "FrameProvenance",
    "NavigationFailureReason",
    "NavigationPhase",
    "NavigationPolicy",
    "NavigationStop",
    "NavigationTransition",
    "NavigationTransitionOutcome",
    "OfflineStepProposal",
    "RouteDirection",
    "RouteEndpoint",
    "RouteEndpointRole",
    "RouteEvaluationContext",
    "RouteIdentity",
    "RoutePlan",
    "RouteProgress",
    "RouteStep",
    "observe_checkpoint",
    "prepare_step",
    "start_route",
]
