"""Development-only validation helpers.

Nothing in this package is part of the production perception or control path.
Validation tools may inject platform adapters at this boundary, while the core
contracts remain importable on every supported development platform.
"""

from __future__ import annotations

from .camera_evaluation import (
    ISSUE31_REQUIRED_LANDMARK_COUNT,
    ISSUE31_REQUIRED_LANDMARK_MATCHES,
    ISSUE31_REQUIRED_MATCHED_ZONES,
    CameraEvaluation,
    CameraLandmarkEvaluation,
    CameraResourceEvaluation,
    evaluate_varrock_east_camera,
)
from .camera_plan import (
    EXPECTED_CLIENT_HEIGHT,
    EXPECTED_CLIENT_WIDTH,
    MAX_CAMERA_ACTIONS,
    MAX_CAMERA_WHEEL_DETENTS,
    MAX_KEY_HOLD_SECONDS,
    MAX_RESET_ZOOM_DWELL_SECONDS,
    MAX_TOTAL_CAMERA_WHEEL_DETENTS,
    MAX_TOTAL_KEY_HOLD_SECONDS,
    REVIEWED_CAMERA_WHEEL_POINT,
    REVIEWED_COMPASS_POINT,
    CameraAction,
    CameraActionReceipt,
    CameraControl,
    CameraHoldKey,
    CameraInputOperation,
    CameraInputReceipt,
    CameraKeyHold,
    CameraPlan,
    CameraPlanError,
    CameraPlanReceipt,
    CameraPlanRunner,
    CameraPreflightError,
    CameraPreflightReceipt,
    CameraReceiptError,
    CameraWheel,
    CompassClick,
    ResetZoomKey,
    Sleeper,
)
from .camera_report import (
    CAMERA_VALIDATION_REPORT_SCHEMA_VERSION,
    CameraReportProvenance,
    CameraReportWriteResult,
    camera_validation_report_bytes,
    write_camera_validation_report,
)
from .camera_session import (
    MINIMUM_CONFIRMATION_FRAMES,
    MINIMUM_REACQUISITION_TRIALS,
    CameraArtifactRecorder,
    CameraFrameArtifact,
    CameraFrameRecord,
    CameraFrameSource,
    CameraSessionResult,
    CameraTrialResult,
    record_frame_digest,
    run_camera_validation_session,
)
from .windows_camera import (
    RealWindowsCameraApi,
    WindowsCameraApi,
    WindowsCameraControl,
    WindowsCameraError,
)

__all__ = [
    "EXPECTED_CLIENT_HEIGHT",
    "EXPECTED_CLIENT_WIDTH",
    "MAX_CAMERA_ACTIONS",
    "MAX_CAMERA_WHEEL_DETENTS",
    "MAX_KEY_HOLD_SECONDS",
    "MAX_RESET_ZOOM_DWELL_SECONDS",
    "MAX_TOTAL_CAMERA_WHEEL_DETENTS",
    "MAX_TOTAL_KEY_HOLD_SECONDS",
    "REVIEWED_CAMERA_WHEEL_POINT",
    "REVIEWED_COMPASS_POINT",
    "CameraAction",
    "CameraActionReceipt",
    "CameraControl",
    "CameraHoldKey",
    "CameraInputOperation",
    "CameraInputReceipt",
    "CameraKeyHold",
    "CameraPlan",
    "CameraPlanError",
    "CameraPlanReceipt",
    "CameraPlanRunner",
    "CameraPreflightError",
    "CameraPreflightReceipt",
    "CameraReceiptError",
    "CameraWheel",
    "CompassClick",
    "ResetZoomKey",
    "Sleeper",
    "CAMERA_VALIDATION_REPORT_SCHEMA_VERSION",
    "ISSUE31_REQUIRED_LANDMARK_COUNT",
    "ISSUE31_REQUIRED_LANDMARK_MATCHES",
    "ISSUE31_REQUIRED_MATCHED_ZONES",
    "MINIMUM_CONFIRMATION_FRAMES",
    "MINIMUM_REACQUISITION_TRIALS",
    "CameraArtifactRecorder",
    "CameraEvaluation",
    "CameraFrameArtifact",
    "CameraFrameRecord",
    "CameraFrameSource",
    "CameraLandmarkEvaluation",
    "CameraReportProvenance",
    "CameraReportWriteResult",
    "CameraResourceEvaluation",
    "CameraSessionResult",
    "CameraTrialResult",
    "RealWindowsCameraApi",
    "WindowsCameraApi",
    "WindowsCameraControl",
    "WindowsCameraError",
    "camera_validation_report_bytes",
    "evaluate_varrock_east_camera",
    "record_frame_digest",
    "run_camera_validation_session",
    "write_camera_validation_report",
]
